spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stupek
    username: "user"
    password: "pass"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none